### ISSUE TITLE
Raw JAVASCRIPT vs. JQUERY

### ISSUE THREAD

**Issue by alibasir** [SaeedehTahmasebi66/chatter-app#4]
https://github.com/SaeedehTahmasebi66/chatter-app/blob/d39bc065983659ba2f5b76945b1165986f7b43e8/main.js#L3

Why have you used raw javascript somewhere and jquery somewhere else?
Is that imposed by edX instructions?

**Comment by SaeedehTahmasebi66** [comment]
Yes... It was imposed by edx.
