### ISSUE TITLE
Weird Statements

### ISSUE THREAD

**Issue by alibasir** [SaeedehTahmasebi66/chatter-app#5]
https://github.com/SaeedehTahmasebi66/chatter-app/blob/d39bc065983659ba2f5b76945b1165986f7b43e8/index.html#L37

Take a careful look at the javascript codes in this division. 
Your code has some problems, also it works. Javascript is very easygoing but we must program accurately.

**Comment by alibasir** [comment]
OK, your change solved the first problem.
The second and dangerous one is that you've passed the argument as something like a variable.
You should pass the `id` name of the HTML element as string.
I've commented your commit  e9e1490 about the problem.

**Comment by SaeedehTahmasebi66** [comment]
-We need a new function to switch between the tab buttons. Call it selectTab().
-Use a nested selector to remove the class .selected from all buttons in the tab bar. You will need jQuery’s removeClass() method. Check jQuery’s documentation if necessary.
-After you removed .selected from all buttons, you add it to the one the user clicked on. You select the element with addClass(). But how do you tell jQuery which button the user just clicked on? Well, every button has an ID and if you click on a button the ID should be passed as an argument to selectTab() and recognized by the jQuery selector. So you should give each tab button an appropriate ID.

**Comment by alibasir** [comment]
OK!
